export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"
export const SIGN_UP = "SIGN_UP"

// USER ACTIONS
export const RISE_TICKET = "RISE_TICKET"
export const GET_USER_TICKETS = "GET_USER_TICKETS"
export const UPDATE_USER = "UPDATE_USER"

//STAFF ACTIONS
export const GET_ALL_TICKETS = "GET_ALL_TICKETS"
export const UPDATE_TICKET = "UPDATE_TICKET"

//SEARCH BAR
export const SEARCH_BY_ID = "SEARCH_BY_ID"
export const SEARCH_BY_NAME = "SEARCH_BY_NAME"

// USER // STAFF
export const GET_TICKET_DETAIL= "GET_TICKET DETAIL"

export const FILTER_BY_DATE= "FILTER_BY_DATE"
export const FILTER_BY_STATUS= "FILTER_BY_STATUS"
export const FILTER_BY_PRIORITY = "FILTER_BY_PRIORITY"

export const SORT_BY_DATE= "SORT_BY_DATE"
export const SORT_BY_STATUS= "SORT_BY_STATUS"
export const SORT_BT_PRIORITY= "SORT_BY_PRIORITY"

export const FILTERED_TICKETS= "FILTERED_TICKETS"


export const SET_ERROR = "SET_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"

export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE"
export const CLEAR_SUCCESS_MESSAGE = "CLEAR_SUCCESS_MESSAGE"